spring:
  datasource:
    username: pyh233
    password:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todaysnewthing
  web:
    resources:
      static-locations: classpath:/templates/
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: LEGACYHTML5
web:
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/templates/, classpath:/public/
server:
  port: 9991
mybatis:
  configuration:
    call-setters-on-nulls: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
